### ISSUE TITLE
Move to IPFS org and add another collaborator

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/dnslink-cloudflare#1]
Should we move this package to `ipfs` org. We have there:

- [`dnslink-dnsimple`](https://github.com/ipfs/dnslink-dnsimple)
- [`dnslink-deploy`](https://github.com/ipfs/dnslink-deploy) (DigitalOcean)

?

Also, I should add someone else as a collaborator on NPM.

/cc @olizilla @lidel

**Comment by lidel** [comment]
I think it should  be other way around: those things are not part of IPFS protocol and belong to ipfs-shipyard :)

Feel free to add me as collaborator – I have some websites on cloudflare and can help with dogfooding this.

**Comment by hacdias** [comment]
Eheh, let's keep it here then. I just added you. I'll close this issue then.
