### ISSUE TITLE
Required permissions arent properly notated

### ISSUE THREAD

**Issue by ShadowJonathan** [ipfs-shipyard/dnslink-cloudflare#41]
Right now, dnslink-cloudflare requires `zone:read` for all zones, and `dns:edit` for one specific zone

I cant remember the first permission being required in previous versions of this library, and the change resulted in me debugging crashing deployments (via `ipfs-deploy`), please describe (in the readme) which permissions are required for the API token, for the library to function.

**Comment by hacdias** [comment]
Just added to the README. Thank you!
